name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: David-Braga878
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_snake: '#40E0D0'            # Azul turquesa
          color_dots: '#C0C0C0,#D8BFD8,#E6E6FA,#FFF0F5,#FFFFFF' # Gradiente sutil nos pontos
          pixel_size: 12                    # Grade mais visível
          motion_speed: 1                   # Velocidade padrão (pode ajustar entre 0.1 a 5)

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
